use super::Cpu;

#[derive(Copy, Clone, PartialEq)]
pub(super) enum AddressingMode {
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndirectX,
    IndirectY,
    Implicit,
    Accumulator,
    Immediate,
    Relative,
}

// Records for the opcode table
pub(super) struct OpcodeRecord {
    pub(super) mnemonic: &'static str,
    pub(super) handler: fn(&mut Cpu),
    pub(super) cycles: u16,
    pub(super) addressing_mode: AddressingMode,
    pub(super) page_cross_penalty: bool,
    pub(super) is_store: bool,
}

// Helper function to represent record more cleanly
const fn opcode(
    mnemonic: &'static str,
    handler: fn(&mut Cpu),
    cycles: u16,
    addressing_mode: AddressingMode,
    page_cross_penalty: bool,
    is_store: bool,
) -> OpcodeRecord {
    OpcodeRecord {
        mnemonic,
        handler,
        cycles,
        addressing_mode,
        page_cross_penalty,
        is_store,
    }
}

pub(super) const OPCODE_TABLE: [OpcodeRecord; 256] = [
    // Note for BRK: Cycles are 7, but to simplify hijacking quirk it is set to 4 here, and then 3 is always added to burn after it checks for hijack
    /* 0x00 */ opcode("BRK", Cpu::brk, 4, AddressingMode::Implicit, false, false),
    /* 0x01 */ opcode("ORA", Cpu::ora, 6, AddressingMode::IndirectX, false, false),
    /* 0x02 */ opcode("KIL", Cpu::kil, 2, AddressingMode::Implicit, false, false),
    /* 0x03 */ opcode("SLO", Cpu::slo, 8, AddressingMode::IndirectX, false, false),
    /* 0x04 */ opcode("NOP", Cpu::nop, 3, AddressingMode::ZeroPage, false, false),
    /* 0x05 */ opcode("ORA", Cpu::ora, 3, AddressingMode::ZeroPage, false, false),
    /* 0x06 */ opcode("ASL", Cpu::asl, 5, AddressingMode::ZeroPage, false, false),
    /* 0x07 */ opcode("SLO", Cpu::slo, 5, AddressingMode::ZeroPage, false, false),
    /* 0x08 */ opcode("PHP", Cpu::php, 3, AddressingMode::Implicit, false, false),
    /* 0x09 */ opcode("ORA", Cpu::ora, 2, AddressingMode::Immediate, false, false),
    /* 0x0A */ opcode("ASL", Cpu::asl, 2, AddressingMode::Accumulator, false, false),
    /* 0x0B */ opcode("ANC", Cpu::anc, 2, AddressingMode::Immediate, false, false),
    /* 0x0C */ opcode("NOP", Cpu::nop, 4, AddressingMode::Absolute, false, false),
    /* 0x0D */ opcode("ORA", Cpu::ora, 4, AddressingMode::Absolute, false, false),
    /* 0x0E */ opcode("ASL", Cpu::asl, 6, AddressingMode::Absolute, false, false),
    /* 0x0F */ opcode("SLO", Cpu::slo, 6, AddressingMode::Absolute, false, false),
    /* 0x10 */ opcode("BPL", Cpu::bpl, 2, AddressingMode::Relative, true, false), // Branching: doesn't use page crossing flag
    /* 0x11 */ opcode("ORA", Cpu::ora, 5, AddressingMode::IndirectY, true, false),
    /* 0x12 */ opcode("KIL", Cpu::kil, 2, AddressingMode::Implicit, false, false),
    /* 0x13 */ opcode("SLO", Cpu::slo, 8, AddressingMode::IndirectY, false, false),
    /* 0x14 */ opcode("NOP", Cpu::nop, 4, AddressingMode::ZeroPageX, false, false),
    /* 0x15 */ opcode("ORA", Cpu::ora, 4, AddressingMode::ZeroPageX, false, false),
    /* 0x16 */ opcode("ASL", Cpu::asl, 6, AddressingMode::ZeroPageX, false, false),
    /* 0x17 */ opcode("SLO", Cpu::slo, 6, AddressingMode::ZeroPageX, false, false),
    /* 0x18 */ opcode("CLC", Cpu::clc, 2, AddressingMode::Implicit, false, false),
    /* 0x19 */ opcode("ORA", Cpu::ora, 4, AddressingMode::AbsoluteY, true, false),
    /* 0x1A */ opcode("NOP", Cpu::nop, 2, AddressingMode::Implicit, false, false),
    /* 0x1B */ opcode("SLO", Cpu::slo, 7, AddressingMode::AbsoluteY, false, false),
    /* 0x1C */ opcode("NOP", Cpu::nop, 4, AddressingMode::AbsoluteX, true, false),
    /* 0x1D */ opcode("ORA", Cpu::ora, 4, AddressingMode::AbsoluteX, true, false),
    /* 0x1E */ opcode("ASL", Cpu::asl, 7, AddressingMode::AbsoluteX, false, false),
    /* 0x1F */ opcode("SLO", Cpu::slo, 7, AddressingMode::AbsoluteX, false, false),
    /* 0x20 */ opcode("JSR", Cpu::jsr, 6, AddressingMode::Absolute, false, false),
    /* 0x21 */ opcode("AND", Cpu::and, 6, AddressingMode::IndirectX, false, false),
    /* 0x22 */ opcode("KIL", Cpu::kil, 2, AddressingMode::Implicit, false, false),
    /* 0x23 */ opcode("RLA", Cpu::rla, 8, AddressingMode::IndirectX, false, false),
    /* 0x24 */ opcode("BIT", Cpu::bit, 3, AddressingMode::ZeroPage, false, false),
    /* 0x25 */ opcode("AND", Cpu::and, 3, AddressingMode::ZeroPage, false, false),
    /* 0x26 */ opcode("ROL", Cpu::rol, 5, AddressingMode::ZeroPage, false, false),
    /* 0x27 */ opcode("RLA", Cpu::rla, 5, AddressingMode::ZeroPage, false, false),
    /* 0x28 */ opcode("PLP", Cpu::plp, 4, AddressingMode::Implicit, false, false),
    /* 0x29 */ opcode("AND", Cpu::and, 2, AddressingMode::Immediate, false, false),
    /* 0x2A */ opcode("ROL", Cpu::rol, 2, AddressingMode::Accumulator, false, false),
    /* 0x2B */ opcode("ANC", Cpu::anc, 2, AddressingMode::Immediate, false, false),
    /* 0x2C */ opcode("BIT", Cpu::bit, 4, AddressingMode::Absolute, false, false),
    /* 0x2D */ opcode("AND", Cpu::and, 4, AddressingMode::Absolute, false, false),
    /* 0x2E */ opcode("ROL", Cpu::rol, 6, AddressingMode::Absolute, false, false),
    /* 0x2F */ opcode("RLA", Cpu::rla, 6, AddressingMode::Absolute, false, false),
    /* 0x30 */ opcode("BMI", Cpu::bmi, 2, AddressingMode::Relative, true, false), // Branching: doesn't use page crossing flag
    /* 0x31 */ opcode("AND", Cpu::and, 5, AddressingMode::IndirectY, true, false),
    /* 0x32 */ opcode("KIL", Cpu::kil, 2, AddressingMode::Implicit, false, false),
    /* 0x33 */ opcode("RLA", Cpu::rla, 8, AddressingMode::IndirectY, false, false),
    /* 0x34 */ opcode("NOP", Cpu::nop, 4, AddressingMode::ZeroPageX, false, false),
    /* 0x35 */ opcode("AND", Cpu::and, 4, AddressingMode::ZeroPageX, false, false),
    /* 0x36 */ opcode("ROL", Cpu::rol, 6, AddressingMode::ZeroPageX, false, false),
    /* 0x37 */ opcode("RLA", Cpu::rla, 6, AddressingMode::ZeroPageX, false, false),
    /* 0x38 */ opcode("SEC", Cpu::sec, 2, AddressingMode::Implicit, false, false),
    /* 0x39 */ opcode("AND", Cpu::and, 4, AddressingMode::AbsoluteY, true, false),
    /* 0x3A */ opcode("NOP", Cpu::nop, 2, AddressingMode::Implicit, false, false),
    /* 0x3B */ opcode("RLA", Cpu::rla, 7, AddressingMode::AbsoluteY, false, false),
    /* 0x3C */ opcode("NOP", Cpu::nop, 4, AddressingMode::AbsoluteX, true, false),
    /* 0x3D */ opcode("AND", Cpu::and, 4, AddressingMode::AbsoluteX, true, false),
    /* 0x3E */ opcode("ROL", Cpu::rol, 7, AddressingMode::AbsoluteX, false, false),
    /* 0x3F */ opcode("RLA", Cpu::rla, 7, AddressingMode::AbsoluteX, false, false),
    /* 0x40 */ opcode("RTI", Cpu::rti, 6, AddressingMode::Implicit, false, false),
    /* 0x41 */ opcode("EOR", Cpu::eor, 6, AddressingMode::IndirectX, false, false),
    /* 0x42 */ opcode("KIL", Cpu::kil, 2, AddressingMode::Implicit, false, false),
    /* 0x43 */ opcode("SRE", Cpu::sre, 8, AddressingMode::IndirectX, false, false),
    /* 0x44 */ opcode("NOP", Cpu::nop, 3, AddressingMode::ZeroPage, false, false),
    /* 0x45 */ opcode("EOR", Cpu::eor, 3, AddressingMode::ZeroPage, false, false),
    /* 0x46 */ opcode("LSR", Cpu::lsr, 5, AddressingMode::ZeroPage, false, false),
    /* 0x47 */ opcode("SRE", Cpu::sre, 5, AddressingMode::ZeroPage, false, false),
    /* 0x48 */ opcode("PHA", Cpu::pha, 3, AddressingMode::Implicit, false, false),
    /* 0x49 */ opcode("EOR", Cpu::eor, 2, AddressingMode::Immediate, false, false),
    /* 0x4A */ opcode("LSR", Cpu::lsr, 2, AddressingMode::Accumulator, false, false),
    /* 0x4B */ opcode("ALR", Cpu::alr, 2, AddressingMode::Immediate, false, false),
    /* 0x4C */ opcode("JMP", Cpu::jmp, 3, AddressingMode::Absolute, false, false),
    /* 0x4D */ opcode("EOR", Cpu::eor, 4, AddressingMode::Absolute, false, false),
    /* 0x4E */ opcode("LSR", Cpu::lsr, 6, AddressingMode::Absolute, false, false),
    /* 0x4F */ opcode("SRE", Cpu::sre, 6, AddressingMode::Absolute, false, false),
    /* 0x50 */ opcode("BVC", Cpu::bvc, 2, AddressingMode::Relative, true, false), // Branching: doesn't use page crossing flag
    /* 0x51 */ opcode("EOR", Cpu::eor, 5, AddressingMode::IndirectY, true, false),
    /* 0x52 */ opcode("KIL", Cpu::kil, 2, AddressingMode::Implicit, false, false),
    /* 0x53 */ opcode("SRE", Cpu::sre, 8, AddressingMode::IndirectY, false, false),
    /* 0x54 */ opcode("NOP", Cpu::nop, 4, AddressingMode::ZeroPageX, false, false),
    /* 0x55 */ opcode("EOR", Cpu::eor, 4, AddressingMode::ZeroPageX, false, false),
    /* 0x56 */ opcode("LSR", Cpu::lsr, 6, AddressingMode::ZeroPageX, false, false),
    /* 0x57 */ opcode("SRE", Cpu::sre, 6, AddressingMode::ZeroPageX, false, false),
    /* 0x58 */ opcode("CLI", Cpu::cli, 2, AddressingMode::Implicit, false, false),
    /* 0x59 */ opcode("EOR", Cpu::eor, 4, AddressingMode::AbsoluteY, true, false),
    /* 0x5A */ opcode("NOP", Cpu::nop, 2, AddressingMode::Implicit, false, false),
    /* 0x5B */ opcode("SRE", Cpu::sre, 7, AddressingMode::AbsoluteY, false, false),
    /* 0x5C */ opcode("NOP", Cpu::nop, 4, AddressingMode::AbsoluteX, true, false),
    /* 0x5D */ opcode("EOR", Cpu::eor, 4, AddressingMode::AbsoluteX, true, false),
    /* 0x5E */ opcode("LSR", Cpu::lsr, 7, AddressingMode::AbsoluteX, false, false),
    /* 0x5F */ opcode("SRE", Cpu::sre, 7, AddressingMode::AbsoluteX, false, false),
    /* 0x60 */ opcode("RTS", Cpu::rts, 6, AddressingMode::Implicit, false, false),
    /* 0x61 */ opcode("ADC", Cpu::adc, 6, AddressingMode::IndirectX, false, false),
    /* 0x62 */ opcode("KIL", Cpu::kil, 2, AddressingMode::Implicit, false, false),
    /* 0x63 */ opcode("RRA", Cpu::rra, 8, AddressingMode::IndirectX, false, false),
    /* 0x64 */ opcode("NOP", Cpu::nop, 3, AddressingMode::ZeroPage, false, false),
    /* 0x65 */ opcode("ADC", Cpu::adc, 3, AddressingMode::ZeroPage, false, false),
    /* 0x66 */ opcode("ROR", Cpu::ror, 5, AddressingMode::ZeroPage, false, false),
    /* 0x67 */ opcode("RRA", Cpu::rra, 5, AddressingMode::ZeroPage, false, false),
    /* 0x68 */ opcode("PLA", Cpu::pla, 4, AddressingMode::Implicit, false, false),
    /* 0x69 */ opcode("ADC", Cpu::adc, 2, AddressingMode::Immediate, false, false),
    /* 0x6A */ opcode("ROR", Cpu::ror, 2, AddressingMode::Accumulator, false, false),
    /* 0x6B */ opcode("ARR", Cpu::arr, 2, AddressingMode::Immediate, false, false),
    /* 0x6C */ opcode("JMP", Cpu::jmp, 5, AddressingMode::Indirect, false, false),
    /* 0x6D */ opcode("ADC", Cpu::adc, 4, AddressingMode::Absolute, false, false),
    /* 0x6E */ opcode("ROR", Cpu::ror, 6, AddressingMode::Absolute, false, false),
    /* 0x6F */ opcode("RRA", Cpu::rra, 6, AddressingMode::Absolute, false, false),
    /* 0x70 */ opcode("BVS", Cpu::bvs, 2, AddressingMode::Relative, true, false), // Branching: doesn't use page crossing flag
    /* 0x71 */ opcode("ADC", Cpu::adc, 5, AddressingMode::IndirectY, true, false),
    /* 0x72 */ opcode("KIL", Cpu::kil, 2, AddressingMode::Implicit, false, false),
    /* 0x73 */ opcode("RRA", Cpu::rra, 8, AddressingMode::IndirectY, false, false),
    /* 0x74 */ opcode("NOP", Cpu::nop, 4, AddressingMode::ZeroPageX, false, false),
    /* 0x75 */ opcode("ADC", Cpu::adc, 4, AddressingMode::ZeroPageX, false, false),
    /* 0x76 */ opcode("ROR", Cpu::ror, 6, AddressingMode::ZeroPageX, false, false),
    /* 0x77 */ opcode("RRA", Cpu::rra, 6, AddressingMode::ZeroPageX, false, false),
    /* 0x78 */ opcode("SEI", Cpu::sei, 2, AddressingMode::Implicit, false, false),
    /* 0x79 */ opcode("ADC", Cpu::adc, 4, AddressingMode::AbsoluteY, true, false),
    /* 0x7A */ opcode("NOP", Cpu::nop, 2, AddressingMode::Implicit, false, false),
    /* 0x7B */ opcode("RRA", Cpu::rra, 7, AddressingMode::AbsoluteY, false, false),
    /* 0x7C */ opcode("NOP", Cpu::nop, 4, AddressingMode::AbsoluteX, true, false),
    /* 0x7D */ opcode("ADC", Cpu::adc, 4, AddressingMode::AbsoluteX, true, false),
    /* 0x7E */ opcode("ROR", Cpu::ror, 7, AddressingMode::AbsoluteX, false, false),
    /* 0x7F */ opcode("RRA", Cpu::rra, 7, AddressingMode::AbsoluteX, false, false),
    /* 0x80 */ opcode("NOP", Cpu::nop, 2, AddressingMode::Immediate, false, false),
    /* 0x81 */ opcode("STA", Cpu::sta, 6, AddressingMode::IndirectX, false, true),
    /* 0x82 */ opcode("NOP", Cpu::nop, 2, AddressingMode::Immediate, false, false),
    /* 0x83 */ opcode("SAX", Cpu::sax, 6, AddressingMode::IndirectX, false, true),
    /* 0x84 */ opcode("STY", Cpu::sty, 3, AddressingMode::ZeroPage, false, true),
    /* 0x85 */ opcode("STA", Cpu::sta, 3, AddressingMode::ZeroPage, false, true),
    /* 0x86 */ opcode("STX", Cpu::stx, 3, AddressingMode::ZeroPage, false, true),
    /* 0x87 */ opcode("SAX", Cpu::sax, 3, AddressingMode::ZeroPage, false, true),
    /* 0x88 */ opcode("DEY", Cpu::dey, 2, AddressingMode::Implicit, false, false),
    /* 0x89 */ opcode("NOP", Cpu::nop, 2, AddressingMode::Immediate, false, false),
    /* 0x8A */ opcode("TXA", Cpu::txa, 2, AddressingMode::Implicit, false, false),
    /* 0x8B */ opcode("XAA", Cpu::xaa, 2, AddressingMode::Immediate, false, false),
    /* 0x8C */ opcode("STY", Cpu::sty, 4, AddressingMode::Absolute, false, true),
    /* 0x8D */ opcode("STA", Cpu::sta, 4, AddressingMode::Absolute, false, true),
    /* 0x8E */ opcode("STX", Cpu::stx, 4, AddressingMode::Absolute, false, true),
    /* 0x8F */ opcode("SAX", Cpu::sax, 4, AddressingMode::Absolute, false, true),
    /* 0x90 */ opcode("BCC", Cpu::bcc, 2, AddressingMode::Relative, true, false), // Branching: doesn't use page crossing flag
    /* 0x91 */ opcode("STA", Cpu::sta, 6, AddressingMode::IndirectY, false, true),
    /* 0x92 */ opcode("KIL", Cpu::kil, 2, AddressingMode::Implicit, false, false),
    /* 0x93 */ opcode("AHX", Cpu::ahx, 6, AddressingMode::IndirectY, false, true),
    /* 0x94 */ opcode("STY", Cpu::sty, 4, AddressingMode::ZeroPageX, false, true),
    /* 0x95 */ opcode("STA", Cpu::sta, 4, AddressingMode::ZeroPageX, false, true),
    /* 0x96 */ opcode("STX", Cpu::stx, 4, AddressingMode::ZeroPageY, false, true),
    /* 0x97 */ opcode("SAX", Cpu::sax, 4, AddressingMode::ZeroPageY, false, true),
    /* 0x98 */ opcode("TYA", Cpu::tya, 2, AddressingMode::Implicit, false, false),
    /* 0x99 */ opcode("STA", Cpu::sta, 5, AddressingMode::AbsoluteY, false, true),
    /* 0x9A */ opcode("TXS", Cpu::txs, 2, AddressingMode::Implicit, false, false),
    /* 0x9B */ opcode("TAS", Cpu::tas, 5, AddressingMode::AbsoluteY, false, true),
    /* 0x9C */ opcode("SHY", Cpu::shy, 5, AddressingMode::AbsoluteX, false, true),
    /* 0x9D */ opcode("STA", Cpu::sta, 5, AddressingMode::AbsoluteX, false, true),
    /* 0x9E */ opcode("SHX", Cpu::shx, 5, AddressingMode::AbsoluteY, false, true),
    /* 0x9F */ opcode("AHX", Cpu::ahx, 5, AddressingMode::AbsoluteY, false, true),
    /* 0xA0 */ opcode("LDY", Cpu::ldy, 2, AddressingMode::Immediate, false, false),
    /* 0xA1 */ opcode("LDA", Cpu::lda, 6, AddressingMode::IndirectX, false, false),
    /* 0xA2 */ opcode("LDX", Cpu::ldx, 2, AddressingMode::Immediate, false, false),
    /* 0xA3 */ opcode("LAX", Cpu::lax, 6, AddressingMode::IndirectX, false, false),
    /* 0xA4 */ opcode("LDY", Cpu::ldy, 3, AddressingMode::ZeroPage, false, false),
    /* 0xA5 */ opcode("LDA", Cpu::lda, 3, AddressingMode::ZeroPage, false, false),
    /* 0xA6 */ opcode("LDX", Cpu::ldx, 3, AddressingMode::ZeroPage, false, false),
    /* 0xA7 */ opcode("LAX", Cpu::lax, 3, AddressingMode::ZeroPage, false, false),
    /* 0xA8 */ opcode("TAY", Cpu::tay, 2, AddressingMode::Implicit, false, false),
    /* 0xA9 */ opcode("LDA", Cpu::lda, 2, AddressingMode::Immediate, false, false),
    /* 0xAA */ opcode("TAX", Cpu::tax, 2, AddressingMode::Implicit, false, false),
    /* 0xAB */ opcode("LAX", Cpu::lax, 2, AddressingMode::Immediate, false, false),
    /* 0xAC */ opcode("LDY", Cpu::ldy, 4, AddressingMode::Absolute, false, false),
    /* 0xAD */ opcode("LDA", Cpu::lda, 4, AddressingMode::Absolute, false, false),
    /* 0xAE */ opcode("LDX", Cpu::ldx, 4, AddressingMode::Absolute, false, false),
    /* 0xAF */ opcode("LAX", Cpu::lax, 4, AddressingMode::Absolute, false, false),
    /* 0xB0 */ opcode("BCS", Cpu::bcs, 2, AddressingMode::Relative, true, false), // Branching: doesn't use page crossing flag
    /* 0xB1 */ opcode("LDA", Cpu::lda, 5, AddressingMode::IndirectY, true, false),
    /* 0xB2 */ opcode("KIL", Cpu::kil, 2, AddressingMode::Implicit, false, false),
    /* 0xB3 */ opcode("LAX", Cpu::lax, 5, AddressingMode::IndirectY, true, false),
    /* 0xB4 */ opcode("LDY", Cpu::ldy, 4, AddressingMode::ZeroPageX, false, false),
    /* 0xB5 */ opcode("LDA", Cpu::lda, 4, AddressingMode::ZeroPageX, false, false),
    /* 0xB6 */ opcode("LDX", Cpu::ldx, 4, AddressingMode::ZeroPageY, false, false),
    /* 0xB7 */ opcode("LAX", Cpu::lax, 4, AddressingMode::ZeroPageY, false, false),
    /* 0xB8 */ opcode("CLV", Cpu::clv, 2, AddressingMode::Implicit, false, false),
    /* 0xB9 */ opcode("LDA", Cpu::lda, 4, AddressingMode::AbsoluteY, true, false),
    /* 0xBA */ opcode("TSX", Cpu::tsx, 2, AddressingMode::Implicit, false, false),
    /* 0xBB */ opcode("LAS", Cpu::las, 4, AddressingMode::AbsoluteY, true, false),
    /* 0xBC */ opcode("LDY", Cpu::ldy, 4, AddressingMode::AbsoluteX, true, false),
    /* 0xBD */ opcode("LDA", Cpu::lda, 4, AddressingMode::AbsoluteX, true, false),
    /* 0xBE */ opcode("LDX", Cpu::ldx, 4, AddressingMode::AbsoluteY, true, false),
    /* 0xBF */ opcode("LAX", Cpu::lax, 4, AddressingMode::AbsoluteY, true, false),
    /* 0xC0 */ opcode("CPY", Cpu::cpy, 2, AddressingMode::Immediate, false, false),
    /* 0xC1 */ opcode("CMP", Cpu::cmp, 6, AddressingMode::IndirectX, false, false),
    /* 0xC2 */ opcode("NOP", Cpu::nop, 2, AddressingMode::Immediate, false, false),
    /* 0xC3 */ opcode("DCP", Cpu::dcp, 8, AddressingMode::IndirectX, false, false),
    /* 0xC4 */ opcode("CPY", Cpu::cpy, 3, AddressingMode::ZeroPage, false, false),
    /* 0xC5 */ opcode("CMP", Cpu::cmp, 3, AddressingMode::ZeroPage, false, false),
    /* 0xC6 */ opcode("DEC", Cpu::dec, 5, AddressingMode::ZeroPage, false, false),
    /* 0xC7 */ opcode("DCP", Cpu::dcp, 5, AddressingMode::ZeroPage, false, false),
    /* 0xC8 */ opcode("INY", Cpu::iny, 2, AddressingMode::Implicit, false, false),
    /* 0xC9 */ opcode("CMP", Cpu::cmp, 2, AddressingMode::Immediate, false, false),
    /* 0xCA */ opcode("DEX", Cpu::dex, 2, AddressingMode::Implicit, false, false),
    /* 0xCB */ opcode("AXS", Cpu::axs, 2, AddressingMode::Immediate, false, false),
    /* 0xCC */ opcode("CPY", Cpu::cpy, 4, AddressingMode::Absolute, false, false),
    /* 0xCD */ opcode("CMP", Cpu::cmp, 4, AddressingMode::Absolute, false, false),
    /* 0xCE */ opcode("DEC", Cpu::dec, 6, AddressingMode::Absolute, false, false),
    /* 0xCF */ opcode("DCP", Cpu::dcp, 6, AddressingMode::Absolute, false, false),
    /* 0xD0 */ opcode("BNE", Cpu::bne, 2, AddressingMode::Relative, true, false), // Branching: doesn't use page crossing flag
    /* 0xD1 */ opcode("CMP", Cpu::cmp, 5, AddressingMode::IndirectY, true, false),
    /* 0xD2 */ opcode("KIL", Cpu::kil, 2, AddressingMode::Implicit, false, false),
    /* 0xD3 */ opcode("DCP", Cpu::dcp, 8, AddressingMode::IndirectY, false, false),
    /* 0xD4 */ opcode("NOP", Cpu::nop, 4, AddressingMode::ZeroPageX, false, false),
    /* 0xD5 */ opcode("CMP", Cpu::cmp, 4, AddressingMode::ZeroPageX, false, false),
    /* 0xD6 */ opcode("DEC", Cpu::dec, 6, AddressingMode::ZeroPageX, false, false),
    /* 0xD7 */ opcode("DCP", Cpu::dcp, 6, AddressingMode::ZeroPageX, false, false),
    /* 0xD8 */ opcode("CLD", Cpu::cld, 2, AddressingMode::Implicit, false, false),
    /* 0xD9 */ opcode("CMP", Cpu::cmp, 4, AddressingMode::AbsoluteY, true, false),
    /* 0xDA */ opcode("NOP", Cpu::nop, 2, AddressingMode::Implicit, false, false),
    /* 0xDB */ opcode("DCP", Cpu::dcp, 7, AddressingMode::AbsoluteY, false, false),
    /* 0xDC */ opcode("NOP", Cpu::nop, 4, AddressingMode::AbsoluteX, true, false),
    /* 0xDD */ opcode("CMP", Cpu::cmp, 4, AddressingMode::AbsoluteX, true, false),
    /* 0xDE */ opcode("DEC", Cpu::dec, 7, AddressingMode::AbsoluteX, false, false),
    /* 0xDF */ opcode("DCP", Cpu::dcp, 7, AddressingMode::AbsoluteX, false, false),
    /* 0xE0 */ opcode("CPX", Cpu::cpx, 2, AddressingMode::Immediate, false, false),
    /* 0xE1 */ opcode("SBC", Cpu::sbc, 6, AddressingMode::IndirectX, false, false),
    /* 0xE2 */ opcode("NOP", Cpu::nop, 2, AddressingMode::Immediate, false, false),
    /* 0xE3 */ opcode("ISC", Cpu::isc, 8, AddressingMode::IndirectX, false, false),
    /* 0xE4 */ opcode("CPX", Cpu::cpx, 3, AddressingMode::ZeroPage, false, false),
    /* 0xE5 */ opcode("SBC", Cpu::sbc, 3, AddressingMode::ZeroPage, false, false),
    /* 0xE6 */ opcode("INC", Cpu::inc, 5, AddressingMode::ZeroPage, false, false),
    /* 0xE7 */ opcode("ISC", Cpu::isc, 5, AddressingMode::ZeroPage, false, false),
    /* 0xE8 */ opcode("INX", Cpu::inx, 2, AddressingMode::Implicit, false, false),
    /* 0xE9 */ opcode("SBC", Cpu::sbc, 2, AddressingMode::Immediate, false, false),
    /* 0xEA */ opcode("NOP", Cpu::nop, 2, AddressingMode::Implicit, false, false),
    /* 0xEB */ opcode("SBC", Cpu::sbc, 2, AddressingMode::Immediate, false, false),
    /* 0xEC */ opcode("CPX", Cpu::cpx, 4, AddressingMode::Absolute, false, false),
    /* 0xED */ opcode("SBC", Cpu::sbc, 4, AddressingMode::Absolute, false, false),
    /* 0xEE */ opcode("INC", Cpu::inc, 6, AddressingMode::Absolute, false, false),
    /* 0xEF */ opcode("ISC", Cpu::isc, 6, AddressingMode::Absolute, false, false),
    /* 0xF0 */ opcode("BEQ", Cpu::beq, 2, AddressingMode::Relative, true, false), // Branching: doesn't use page crossing flag
    /* 0xF1 */ opcode("SBC", Cpu::sbc, 5, AddressingMode::IndirectY, true, false),
    /* 0xF2 */ opcode("KIL", Cpu::kil, 2, AddressingMode::Implicit, false, false),
    /* 0xF3 */ opcode("ISC", Cpu::isc, 8, AddressingMode::IndirectY, false, false),
    /* 0xF4 */ opcode("NOP", Cpu::nop, 4, AddressingMode::ZeroPageX, false, false),
    /* 0xF5 */ opcode("SBC", Cpu::sbc, 4, AddressingMode::ZeroPageX, false, false),
    /* 0xF6 */ opcode("INC", Cpu::inc, 6, AddressingMode::ZeroPageX, false, false),
    /* 0xF7 */ opcode("ISC", Cpu::isc, 6, AddressingMode::ZeroPageX, false, false),
    /* 0xF8 */ opcode("SED", Cpu::sed, 2, AddressingMode::Implicit, false, false),
    /* 0xF9 */ opcode("SBC", Cpu::sbc, 4, AddressingMode::AbsoluteY, true, false),
    /* 0xFA */ opcode("NOP", Cpu::nop, 2, AddressingMode::Implicit, false, false),
    /* 0xFB */ opcode("ISC", Cpu::isc, 7, AddressingMode::AbsoluteY, false, false),
    /* 0xFC */ opcode("NOP", Cpu::nop, 4, AddressingMode::AbsoluteX, true, false),
    /* 0xFD */ opcode("SBC", Cpu::sbc, 4, AddressingMode::AbsoluteX, true, false),
    /* 0xFE */ opcode("INC", Cpu::inc, 7, AddressingMode::AbsoluteX, false, false),
    /* 0xFF */ opcode("ISC", Cpu::isc, 7, AddressingMode::AbsoluteX, false, false),
];
