use super::Cpu;
pub(super) enum AddressingMode {
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndirectX,
    IndirectY,
    Implicit,
    Accumulator,
    Immediate,
    Relative,
}

// Records for the opcode table
pub(super) struct OpcodeRecord {
    mnemonic: &'static str,
    function: fn(&mut Cpu),
    cycles: u8,
    addressing_mode: AddressingMode,
    page_cross_penalty: bool,
}

// Helper function to represent record more cleanly
const fn opcode(
    mnemonic: &'static str,
    function: fn(&mut Cpu),
    cycles: u8,
    addressing_mode: AddressingMode,
    page_cross_penalty: bool,
) -> OpcodeRecord {
    OpcodeRecord {
        mnemonic,
        function,
        cycles,
        addressing_mode,
        page_cross_penalty,
    }
}

pub(super) const OPCODE_TABLE: [OpcodeRecord; 48] = [
    /* 0x00 */ opcode("BRK", Cpu::brk, 7, AddressingMode::Implicit, false),
    /* 0x01 */ opcode("ORA", Cpu::ora, 6, AddressingMode::IndirectX, false),
    /* 0x02 */ opcode("KIL", Cpu::kil, 0, AddressingMode::Implicit, false),
    /* 0x03 */ opcode("SLO", Cpu::slo, 8, AddressingMode::IndirectX, false),
    /* 0x04 */ opcode("NOP", Cpu::nop, 3, AddressingMode::ZeroPage, false),
    /* 0x05 */ opcode("ORA", Cpu::ora, 3, AddressingMode::ZeroPage, false),
    /* 0x06 */ opcode("ASL", Cpu::asl, 5, AddressingMode::ZeroPage, false),
    /* 0x07 */ opcode("SLO", Cpu::slo, 5, AddressingMode::ZeroPage, false),
    /* 0x08 */ opcode("PHP", Cpu::php, 3, AddressingMode::Implicit, false),
    /* 0x09 */ opcode("ORA", Cpu::ora, 2, AddressingMode::Immediate, false),
    /* 0x0A */ opcode("ASL", Cpu::asl, 2, AddressingMode::Accumulator, false),
    /* 0x0B */ opcode("ANC", Cpu::anc, 2, AddressingMode::Immediate, false),
    /* 0x0C */ opcode("NOP", Cpu::nop, 4, AddressingMode::Absolute, false),
    /* 0x0D */ opcode("ORA", Cpu::ora, 4, AddressingMode::Absolute, false),
    /* 0x0E */ opcode("ASL", Cpu::asl, 6, AddressingMode::Absolute, false),
    /* 0x0F */ opcode("SLO", Cpu::slo, 6, AddressingMode::Absolute, false),
    /* 0x10 */ opcode("BPL", Cpu::bpl, 2, AddressingMode::Relative, true),
    /* 0x11 */ opcode("ORA", Cpu::ora, 5, AddressingMode::IndirectY, true),
    /* 0x12 */ opcode("KIL", Cpu::kil, 0, AddressingMode::Implicit, false),
    /* 0x13 */ opcode("SLO", Cpu::slo, 8, AddressingMode::IndirectY, false),
    /* 0x14 */ opcode("NOP", Cpu::nop, 4, AddressingMode::ZeroPageX, false),
    /* 0x15 */ opcode("ORA", Cpu::ora, 4, AddressingMode::ZeroPageX, false),
    /* 0x16 */ opcode("ASL", Cpu::asl, 6, AddressingMode::ZeroPageX, false),
    /* 0x17 */ opcode("SLO", Cpu::ora, 6, AddressingMode::ZeroPageX, false),
    /* 0x18 */ opcode("CLC", Cpu::clc, 2, AddressingMode::Implicit, false),
    /* 0x19 */ opcode("ORA", Cpu::ora, 4, AddressingMode::AbsoluteY, true),
    /* 0x1A */ opcode("NOP", Cpu::nop, 2, AddressingMode::Implicit, false),
    /* 0x1B */ opcode("SLO", Cpu::slo, 7, AddressingMode::AbsoluteY, false),
    /* 0x1C */ opcode("NOP", Cpu::nop, 4, AddressingMode::AbsoluteX, true),
    /* 0x1D */ opcode("ORA", Cpu::ora, 4, AddressingMode::AbsoluteX, true),
    /* 0x1E */ opcode("ASL", Cpu::asl, 7, AddressingMode::AbsoluteX, false),
    /* 0x1F */ opcode("SLO", Cpu::slo, 7, AddressingMode::AbsoluteX, false),
    /* 0x20 */ opcode("JSR", Cpu::jsr, 6, AddressingMode::Absolute, false),
    /* 0x21 */ opcode("AND", Cpu::and, 6, AddressingMode::IndirectX, false),
    /* 0x22 */ opcode("KIL", Cpu::kil, 0, AddressingMode::Implicit, false),
    /* 0x23 */ opcode("RLA", Cpu::rla, 8, AddressingMode::IndirectX, false),
    /* 0x24 */ opcode("BIT", Cpu::bit, 3, AddressingMode::ZeroPage, false),
    /* 0x25 */ opcode("AND", Cpu::and, 3, AddressingMode::ZeroPage, false),
    /* 0x26 */ opcode("ROL", Cpu::rol, 5, AddressingMode::ZeroPage, false),
    /* 0x27 */ opcode("RLA", Cpu::rla, 5, AddressingMode::ZeroPage, false),
    /* 0x28 */ opcode("PLP", Cpu::plp, 4, AddressingMode::Implicit, false),
    /* 0x29 */ opcode("AND", Cpu::and, 2, AddressingMode::Immediate, false),
    /* 0x2A */ opcode("ROL", Cpu::rol, 2, AddressingMode::Implicit, false),
    /* 0x2B */ opcode("ANC", Cpu::anc, 2, AddressingMode::Immediate, false),
    /* 0x2C */ opcode("BIT", Cpu::bit, 4, AddressingMode::Absolute, false),
    /* 0x2D */ opcode("AND", Cpu::and, 4, AddressingMode::Absolute, false),
    /* 0x2E */ opcode("ROL", Cpu::rol, 6, AddressingMode::Absolute, false),
    /* 0x2F */ opcode("RLA", Cpu::rla, 6, AddressingMode::Absolute, false),
];
